using EduManageLms.Api.Domain; using MongoDB.Driver;
namespace EduManageLms.Api.Infrastructure;
public sealed class IndexInitializer(MongoContext db,ILogger<IndexInitializer> log){public async Task InitializeAsync(CancellationToken ct=default){
 await db.Users.Indexes.CreateManyAsync([new CreateIndexModel<User>(Builders<User>.IndexKeys.Ascending(x=>x.Username),new(){Unique=true,Name="ux_users_username"}),new CreateIndexModel<User>(Builders<User>.IndexKeys.Ascending(x=>x.Email),new(){Unique=true,Name="ux_users_email"}),new CreateIndexModel<User>(Builders<User>.IndexKeys.Ascending(x=>x.Role).Ascending(x=>x.Status),new(){Name="ix_users_role_status"})],ct);
 await db.Students.Indexes.CreateOneAsync(new CreateIndexModel<Student>(Builders<Student>.IndexKeys.Ascending(x=>x.StudentCode),new(){Unique=true,Name="ux_students_studentCode"}),cancellationToken:ct);
 await db.Lecturers.Indexes.CreateOneAsync(new CreateIndexModel<Lecturer>(Builders<Lecturer>.IndexKeys.Ascending(x=>x.LecturerCode),new(){Unique=true,Name="ux_lecturers_lecturerCode"}),cancellationToken:ct);
 await db.Courses.Indexes.CreateOneAsync(new CreateIndexModel<Course>(Builders<Course>.IndexKeys.Ascending(x=>x.CourseCode),new(){Unique=true,Name="ux_courses_courseCode"}),cancellationToken:ct);
 await db.ClassSections.Indexes.CreateManyAsync([new CreateIndexModel<ClassSection>(Builders<ClassSection>.IndexKeys.Ascending(x=>x.ClassSectionCode),new(){Unique=true,Name="ux_sections_code"}),new CreateIndexModel<ClassSection>(Builders<ClassSection>.IndexKeys.Ascending(x=>x.AcademicYearId).Ascending(x=>x.SemesterId).Ascending(x=>x.LecturerId),new(){Name="ix_sections_year_semester_lecturer"})],ct);
 await db.Notifications.Indexes.CreateManyAsync([new CreateIndexModel<Notification>(Builders<Notification>.IndexKeys.Ascending(x=>x.RecipientIds),new(){Name="ix_notifications_recipients"}),new CreateIndexModel<Notification>(Builders<Notification>.IndexKeys.Descending(x=>x.CreatedAt),new(){Name="ix_notifications_createdAt"})],ct);
 await db.AuditLogs.Indexes.CreateOneAsync(new CreateIndexModel<AuditLog>(Builders<AuditLog>.IndexKeys.Descending(x=>x.CreatedAt),new(){Name="ix_audit_createdAt"}),cancellationToken:ct); log.LogInformation("MongoDB indexes initialized"); }}
