import { Component, OnInit, signal } from '@angular/core';
import { ApiService } from '../../core/services/api.service';
import { AdminReport, ChartItem } from '../../core/models/portal.models';
import { PageHeaderComponent } from '../../shared/page-header.component';
import { StatCardComponent } from '../../shared/stat-card.component';

@Component({ standalone: true, imports: [PageHeaderComponent, StatCardComponent], template: `
<app-page-header title="Báo cáo đào tạo" subtitle="Tổng hợp dữ liệu thật từ MongoDB và các pipeline thống kê."><button class="secondary-button" (click)="print()"><span class="material-symbols-outlined">print</span> In báo cáo</button></app-page-header>
@if(report();as data){<div class="stats-grid">@for(card of data.cards;track card.label){<app-stat-card [label]="card.label" [value]="card.value" [icon]="card.icon" [trend]="card.trend||''" [tone]="card.tone||'primary'"/>}</div><div class="dashboard-grid"><article class="panel"><div class="panel-heading"><div><h3>Sinh viên theo khoa</h3><p>Cơ cấu người học hiện tại</p></div></div><div class="bar-chart">@for(item of data.studentsByFaculty;track item.label){<div class="bar-row"><span>{{item.label}}</span><div><i [style.width.%]="percent(item,data.studentsByFaculty)"></i></div><b>{{item.value}}</b></div>}</div></article><article class="panel"><div class="panel-heading"><div><h3>Trạng thái bảng điểm</h3><p>Tiến độ nhập và công bố</p></div></div><div class="bar-chart">@for(item of data.gradeStatus;track item.label){<div class="bar-row"><span>{{item.label}}</span><div><i [style.width.%]="percent(item,data.gradeStatus)"></i></div><b>{{item.value}}</b></div>}</div></article><article class="panel"><div class="panel-heading"><div><h3>Trạng thái học tập</h3></div></div><div class="bar-chart">@for(item of data.learningStatus;track item.label){<div class="bar-row"><span>{{item.label}}</span><div><i [style.width.%]="percent(item,data.learningStatus)"></i></div><b>{{item.value}}</b></div>}</div></article><article class="panel"><div class="panel-heading"><div><h3>Mức đạt CLO trung bình</h3><p>Tính bằng MongoDB Aggregation</p></div></div><div class="bar-chart">@for(item of data.cloAchievement;track item.label){<div class="bar-row"><span>{{item.label}}</span><div><i [style.width.%]="item.value"></i></div><b>{{item.value}}%</b></div>}</div></article><article class="panel span-2"><div class="panel-heading"><div><h3>Hoạt động gần đây</h3></div></div><div class="activity-list">@for(activity of data.recentActivities;track $index){<div><span class="activity-icon material-symbols-outlined">{{activity.icon}}</span><div><b>{{activity.title}}</b><p>{{activity.description}}</p></div><time>{{activity.time}}</time></div>}</div></article></div>}@else{<div class="skeleton-grid"><div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div></div>}
` })
export class ReportsComponent implements OnInit { report = signal<AdminReport | null>(null); constructor(private api: ApiService) {} ngOnInit() { this.api.get<AdminReport>('/admin/reports').subscribe(response => this.report.set(response.data)); } percent(item: ChartItem, list: ChartItem[]) { const max = Math.max(...list.map(x => x.value), 1); return item.value / max * 100; } print() { window.print(); } }
