using EduManageLms.Api.Common; using EduManageLms.Api.Infrastructure; using MongoDB.Bson; using MongoDB.Driver;
namespace EduManageLms.Api.Application;
public sealed class AdminResourceService(MongoContext db):IAdminResourceService{
 public async Task<PagedResult<Dictionary<string,object?>>> ListAsync(string resource,string? search,int page,int size,CancellationToken ct){var c=Collection(resource);var f=Builders<BsonDocument>.Filter.Ne("isDeleted",true);if(!string.IsNullOrWhiteSpace(search)){var rx=new BsonRegularExpression(search,"i");f&=Builders<BsonDocument>.Filter.Or(Builders<BsonDocument>.Filter.Regex("fullName",rx),Builders<BsonDocument>.Filter.Regex("email",rx),Builders<BsonDocument>.Filter.Regex(CodeField(resource),rx),Builders<BsonDocument>.Filter.Regex("courseName",rx));}var total=await c.CountDocumentsAsync(f,cancellationToken:ct);var docs=await c.Find(f).Skip((page-1)*size).Limit(size).ToListAsync(ct);return PagedResult<Dictionary<string,object?>>.Create(docs.Select(Map).ToList(),page,size,total);}
 public async Task<Dictionary<string,object?>> CreateAsync(string resource,Dictionary<string,object?> body,CancellationToken ct){var d=ToBson(body);d["_id"]=ObjectId.GenerateNewId();d["createdAt"]=DateTime.UtcNow;d["updatedAt"]=DateTime.UtcNow;d["isDeleted"]=false;await Collection(resource).InsertOneAsync(d,cancellationToken:ct);return Map(d);}
 public async Task<Dictionary<string,object?>> UpdateAsync(string resource,string id,Dictionary<string,object?> body,CancellationToken ct){if(!ObjectId.TryParse(id,out var oid))throw new AppException("Id không hợp lệ");var d=ToBson(body);d.Remove("id");d.Remove("_id");d["updatedAt"]=DateTime.UtcNow;var update=new BsonDocument("$set",d);var result=await Collection(resource).UpdateOneAsync(new BsonDocument("_id",oid),update,cancellationToken:ct);if(result.MatchedCount==0)throw new NotFoundException();var doc=await Collection(resource).Find(new BsonDocument("_id",oid)).FirstAsync(ct);return Map(doc);}
 public async Task DeleteAsync(string resource,string id,CancellationToken ct){if(!ObjectId.TryParse(id,out var oid))throw new AppException("Id không hợp lệ");var r=await Collection(resource).UpdateOneAsync(new BsonDocument("_id",oid),new BsonDocument("$set",new BsonDocument{{"isDeleted",true},{"updatedAt",DateTime.UtcNow}}),cancellationToken:ct);if(r.MatchedCount==0)throw new NotFoundException();}
 private IMongoCollection<BsonDocument> Collection(string r)=>r switch{"users"=>db.Database.GetCollection<BsonDocument>("users"),"students"=>db.Database.GetCollection<BsonDocument>("students"),"lecturers"=>db.Database.GetCollection<BsonDocument>("lecturers"),"courses"=>db.Database.GetCollection<BsonDocument>("courses"),"class-sections"=>db.Database.GetCollection<BsonDocument>("classSections"),_=>throw new NotFoundException("Tài nguyên không được hỗ trợ")};private static string CodeField(string r)=>r switch{"students"=>"studentCode","lecturers"=>"lecturerCode","courses"=>"courseCode","class-sections"=>"classSectionCode",_=>"username"};
 private static Dictionary<string,object?> Map(BsonDocument d){var x=d.Elements.ToDictionary(e=>e.Name=="_id"?"id":e.Name,e=>BsonTypeMapper.MapToDotNetValue(e.Value));return x;}
 private static BsonDocument ToBson(Dictionary<string,object?> x)=>new(x.Where(p=>p.Value is not null).Select(p=>new BsonElement(p.Key,ConvertValue(p.Value))));
 private static BsonValue ConvertValue(object? value){if(value is null)return BsonNull.Value;if(value is System.Text.Json.JsonElement j)return j.ValueKind switch{System.Text.Json.JsonValueKind.String=>j.TryGetDateTime(out var dt)?new BsonDateTime(dt):new BsonString(j.GetString()??string.Empty),System.Text.Json.JsonValueKind.Number=>j.TryGetInt64(out var l)?new BsonInt64(l):new BsonDouble(j.GetDouble()),System.Text.Json.JsonValueKind.True=>BsonBoolean.True,System.Text.Json.JsonValueKind.False=>BsonBoolean.False,System.Text.Json.JsonValueKind.Array=>new BsonArray(j.EnumerateArray().Select(x=>ConvertValue(x))),System.Text.Json.JsonValueKind.Object=>new BsonDocument(j.EnumerateObject().Select(x=>new BsonElement(x.Name,ConvertValue(x.Value)))),_=>BsonNull.Value};return BsonValue.Create(value);}
}
