import { Component, OnInit, input, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { ApiService } from '../../core/services/api.service';
import { AssignmentItem } from '../../core/models/portal.models';
import { PageHeaderComponent } from '../../shared/page-header.component';
import { ToastService } from '../../core/services/toast.service';

@Component({ standalone: true, imports: [DatePipe, FormsModule, RouterLink, PageHeaderComponent], template: `
<app-page-header title="Bài tập" subtitle="Tạo bài tập, ánh xạ CLO, theo dõi bài nộp và chấm điểm."><button class="primary-button" (click)="open()"><span class="material-symbols-outlined">add_task</span> Tạo bài tập</button></app-page-header><div class="course-grade-grid">@for(item of items();track item.id){<article class="panel"><div class="panel-heading"><div><span class="eyebrow">{{item.courseCode}}</span><h3>{{item.title}}</h3><p>{{item.content}}</p></div><span class="badge" [class.success]="item.status==='Open'">{{item.status}}</span></div><div class="detail-list"><div><span>Điểm tối đa</span><b>{{item.maxScore}}</b></div><div><span>Hạn nộp</span><b>{{item.dueAt|date:'dd/MM/yyyy HH:mm'}}</b></div><div><span>Bài đã nộp</span><b>{{item.submissionCount}}</b></div><div><span>CLO</span><b>{{item.cloCodes.join(', ')}}</b></div></div><div class="class-actions"><a class="primary-button" [routerLink]="['/lecturer/assignments',item.id,'submissions']">Xem bài nộp</a><button class="text-button" (click)="open(item)">Sửa</button><button class="text-button danger-text" (click)="remove(item)">Xóa</button></div></article>}@empty{<article class="panel empty-state"><span class="material-symbols-outlined">assignment</span><h3>Chưa có bài tập</h3></article>}</div>
@if(modal()){<div class="modal-backdrop" (click)="modal.set(false)"><form class="modal" (click)="$event.stopPropagation()" (submit)="$event.preventDefault();save()"><div class="modal-heading"><div><h3>{{form.id?'Cập nhật':'Tạo'}} bài tập</h3></div><button type="button" class="icon-button" (click)="modal.set(false)"><span class="material-symbols-outlined">close</span></button></div><div class="form-grid"><label class="full-row">Tiêu đề<input [(ngModel)]="form.title" name="title"/></label><label class="full-row">Nội dung<textarea [(ngModel)]="form.content" name="content" rows="5"></textarea></label><label>Điểm tối đa<input type="number" [(ngModel)]="form.maxScore" name="maxScore"/></label><label>Cột điểm liên kết<input [(ngModel)]="form.linkedComponentId" name="linkedComponentId" placeholder="BT"/></label><label>Ngày mở<input type="datetime-local" [(ngModel)]="form.openAt" name="openAt"/></label><label>Hạn nộp<input type="datetime-local" [(ngModel)]="form.dueAt" name="dueAt"/></label><label>CLO, cách nhau dấu phẩy<input [(ngModel)]="cloText" name="cloText"/></label><label>Trạng thái<select [(ngModel)]="form.status" name="status"><option>Draft</option><option>Open</option><option>Closed</option></select></label><label class="checkbox"><input type="checkbox" [(ngModel)]="form.allowLate" name="allowLate"/> Cho phép nộp trễ</label><label>Trừ điểm nộp trễ (%)<input type="number" [(ngModel)]="form.latePenaltyPercent" name="latePenaltyPercent"/></label><label class="full-row">File/liên kết đính kèm<input [(ngModel)]="form.attachmentUrl" name="attachmentUrl"/></label></div><div class="modal-actions"><button type="button" class="secondary-button" (click)="modal.set(false)">Hủy</button><button class="primary-button">Lưu bài tập</button></div></form></div>}
` })
export class LecturerAssignmentsComponent implements OnInit { id = input.required<string>(); items = signal<AssignmentItem[]>([]); modal = signal(false); form: any = {}; cloText = ''; constructor(private api: ApiService, private toast: ToastService) {} ngOnInit() { this.load(); } load() { this.api.get<AssignmentItem[]>('/lecturer/assignments', { classSectionId: this.id() }).subscribe(response => this.items.set(response.data)); } open(item?: AssignmentItem) { this.form = item ? { ...item, openAt: this.local(item.openAt), dueAt: this.local(item.dueAt) } : { classSectionId: this.id(), title: '', content: '', attachmentUrl: '', maxScore: 10, openAt: this.local(new Date().toISOString()), dueAt: this.local(new Date(Date.now() + 7 * 86400000).toISOString()), allowLate: false, latePenaltyPercent: 0, linkedComponentId: 'BT', status: 'Open' }; this.cloText = item?.cloCodes.join(', ') || 'CLO1'; this.modal.set(true); } save() { const id = this.form.id; const body = { ...this.form, classSectionId: this.id(), openAt: new Date(this.form.openAt).toISOString(), dueAt: new Date(this.form.dueAt).toISOString(), cloCodes: this.cloText.split(',').map(x => x.trim()).filter(Boolean) }; delete body.id; delete body.submissionCount; const call = id ? this.api.put(`/lecturer/assignments/${id}`, body) : this.api.post('/lecturer/assignments', body); call.subscribe({ next: () => { this.toast.show('Đã lưu bài tập', 'success'); this.modal.set(false); this.load(); }, error: error => this.toast.show(error.error?.message || 'Không thể lưu', 'error') }); } remove(item: AssignmentItem) { if (!confirm('Xóa bài tập này?')) return; this.api.delete(`/lecturer/assignments/${item.id}`).subscribe(() => this.load()); } private local(value?: string) { if (!value) return ''; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); } }
