import { Component, OnInit, input, signal } from '@angular/core';
import { ApiService } from '../../core/services/api.service';
import { ClassStatistics } from '../../core/models/portal.models';
import { PageHeaderComponent } from '../../shared/page-header.component';

@Component({ standalone: true, imports: [PageHeaderComponent], template: `
<app-page-header title="Thống kê lớp" subtitle="Số liệu được tổng hợp từ điểm thành phần bằng MongoDB Aggregation Pipeline."><button class="secondary-button" (click)="print()"><span class="material-symbols-outlined">download</span> Xuất báo cáo</button></app-page-header>@if(data();as item){<div class="stats-grid"><article class="stat-card"><div class="stat-icon"><span class="material-symbols-outlined">groups</span></div><div><span>Sĩ số</span><strong>{{item.studentCount}}</strong></div></article><article class="stat-card success"><div class="stat-icon"><span class="material-symbols-outlined">trending_up</span></div><div><span>Điểm trung bình</span><strong>{{item.average}}</strong><small>Cao nhất {{item.highest}}</small></div></article><article class="stat-card warning"><div class="stat-icon"><span class="material-symbols-outlined">analytics</span></div><div><span>Trung vị / Độ lệch</span><strong>{{item.median}}</strong><small>σ = {{item.standardDeviation}}</small></div></article><article class="stat-card" [class.danger]="item.passRate<60"><div class="stat-icon"><span class="material-symbols-outlined">verified</span></div><div><span>Tỷ lệ đạt</span><strong>{{item.passRate}}%</strong><small>{{item.passed}} đạt · {{item.failed}} chưa đạt</small></div></article></div><div class="dashboard-grid"><article class="panel"><div class="panel-heading"><div><h3>Phân bố điểm</h3><p>{{item.classSectionCode}} - {{item.courseName}}</p></div></div><div class="bar-chart">@for(bar of item.distribution;track bar.label){<div class="bar-row"><span>{{bar.label}}</span><div><i [style.width.%]="bar.value/item.studentCount*100"></i></div><b>{{bar.value}}</b></div>}</div></article><article class="panel"><div class="panel-heading"><div><h3>Top sinh viên</h3></div></div><div class="activity-list">@for(student of item.topStudents;track student.studentId){<div><span class="activity-icon material-symbols-outlined">workspace_premium</span><div><b>{{student.studentCode}} - {{student.fullName}}</b><p>Điểm tổng kết</p></div><strong>{{student.finalScore}}</strong></div>}</div></article><article class="panel span-2"><div class="panel-heading"><div><h3>Sinh viên có nguy cơ không đạt</h3><p>Cần hỗ trợ hoặc bổ sung điểm thành phần</p></div></div><div class="table-wrap"><table><thead><tr><th>Mã SV</th><th>Họ tên</th><th>Điểm hiện tại</th><th>Điểm chữ</th><th>Trạng thái</th></tr></thead><tbody>@for(student of item.atRiskStudents;track student.studentId){<tr><td>{{student.studentCode}}</td><td>{{student.fullName}}</td><td>{{student.finalScore}}</td><td>{{student.letterGrade}}</td><td><span class="badge danger">Nguy cơ</span></td></tr>}@empty{<tr><td colspan="5" class="empty">Không có sinh viên nguy cơ</td></tr>}</tbody></table></div></article></div>}
` })
export class ClassStatisticsComponent implements OnInit { id = input.required<string>(); data = signal<ClassStatistics | null>(null); constructor(private api: ApiService) {} ngOnInit() { this.api.get<ClassStatistics>(`/lecturer/classes/${this.id()}/statistics`).subscribe(response => this.data.set(response.data)); } print() { window.print(); } }
