import { Component, OnInit, input, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../core/services/api.service';
import { MaterialItem } from '../../core/models/portal.models';
import { PageHeaderComponent } from '../../shared/page-header.component';
import { ToastService } from '../../core/services/toast.service';

@Component({ standalone: true, imports: [DatePipe, FormsModule, PageHeaderComponent], template: `
<app-page-header title="Tài liệu học tập" subtitle="Quản lý bài giảng, đề cương, liên kết và thời gian hiển thị."><button class="primary-button" (click)="open()"><span class="material-symbols-outlined">add</span> Thêm tài liệu</button></app-page-header><div class="course-grade-grid">@for(item of items();track item.id){<article class="panel"><div class="panel-heading"><div><span class="eyebrow">{{item.courseCode}} · {{item.chapter}}</span><h3>{{item.title}}</h3><p>{{item.description}}</p></div><span class="badge" [class.success]="item.status==='Published'">{{item.status}}</span></div><div class="detail-list"><div><span>Loại</span><b>{{item.resourceType}}</b></div><div><span>Danh mục</span><b>{{item.category}}</b></div><div><span>Hiển thị từ</span><b>{{item.visibleFrom|date:'dd/MM/yyyy'}}</b></div><div><span>Lượt xem</span><b>{{item.viewCount}}</b></div></div><div class="class-actions"><a class="secondary-button" [href]="item.resourceUrl" target="_blank">Mở tài liệu</a><button class="text-button" (click)="open(item)">Sửa</button><button class="text-button danger-text" (click)="remove(item)">Xóa</button></div></article>}@empty{<article class="panel empty-state"><span class="material-symbols-outlined">folder_open</span><h3>Chưa có tài liệu</h3></article>}</div>
@if(modal()){<div class="modal-backdrop" (click)="modal.set(false)"><form class="modal" (click)="$event.stopPropagation()" (submit)="$event.preventDefault();save()"><div class="modal-heading"><div><h3>{{form.id?'Cập nhật':'Thêm'}} tài liệu</h3></div><button type="button" class="icon-button" (click)="modal.set(false)"><span class="material-symbols-outlined">close</span></button></div><div class="form-grid"><label class="full-row">Tiêu đề<input [(ngModel)]="form.title" name="title"/></label><label class="full-row">Mô tả<textarea [(ngModel)]="form.description" name="description" rows="4"></textarea></label><label>Danh mục<input [(ngModel)]="form.category" name="category"/></label><label>Chương/chủ đề<input [(ngModel)]="form.chapter" name="chapter"/></label><label>Loại tài nguyên<select [(ngModel)]="form.resourceType" name="resourceType"><option>Link</option><option>PDF</option><option>Word</option><option>PowerPoint</option></select></label><label>Trạng thái<select [(ngModel)]="form.status" name="status"><option>Draft</option><option>Published</option></select></label><label class="full-row">Đường dẫn<input [(ngModel)]="form.resourceUrl" name="resourceUrl"/></label><label>Hiển thị từ<input type="datetime-local" [(ngModel)]="form.visibleFrom" name="visibleFrom"/></label><label>Hết hạn<input type="datetime-local" [(ngModel)]="form.visibleUntil" name="visibleUntil"/></label></div><div class="modal-actions"><button type="button" class="secondary-button" (click)="modal.set(false)">Hủy</button><button class="primary-button">Lưu tài liệu</button></div></form></div>}
` })
export class LecturerMaterialsComponent implements OnInit { id = input.required<string>(); items = signal<MaterialItem[]>([]); modal = signal(false); form: any = {}; constructor(private api: ApiService, private toast: ToastService) {} ngOnInit() { this.load(); } load() { this.api.get<MaterialItem[]>('/lecturer/materials', { classSectionId: this.id() }).subscribe(response => this.items.set(response.data)); } open(item?: MaterialItem) { this.form = item ? { ...item, visibleFrom: this.local(item.visibleFrom), visibleUntil: this.local(item.visibleUntil) } : { classSectionId: this.id(), title: '', description: '', category: 'Bài giảng', chapter: '', resourceType: 'Link', resourceUrl: '', visibleFrom: this.local(new Date().toISOString()), visibleUntil: '', status: 'Published' }; this.modal.set(true); } save() { const id = this.form.id; const body = { ...this.form, classSectionId: this.id(), visibleFrom: this.form.visibleFrom ? new Date(this.form.visibleFrom).toISOString() : null, visibleUntil: this.form.visibleUntil ? new Date(this.form.visibleUntil).toISOString() : null }; delete body.id; const call = id ? this.api.put(`/lecturer/materials/${id}`, body) : this.api.post('/lecturer/materials', body); call.subscribe({ next: () => { this.toast.show('Đã lưu tài liệu', 'success'); this.modal.set(false); this.load(); }, error: error => this.toast.show(error.error?.message || 'Không thể lưu', 'error') }); } remove(item: MaterialItem) { if (!confirm('Xóa tài liệu này?')) return; this.api.delete(`/lecturer/materials/${item.id}`).subscribe(() => this.load()); } private local(value?: string) { if (!value) return ''; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); } }
