import { Component, OnInit, input, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../core/services/api.service';
import { SubmissionItem } from '../../core/models/portal.models';
import { PageHeaderComponent } from '../../shared/page-header.component';
import { ToastService } from '../../core/services/toast.service';

@Component({ standalone: true, imports: [DatePipe, FormsModule, PageHeaderComponent], template: `
<app-page-header title="Chấm bài tập" subtitle="Xem bài nộp, nhập điểm, nhận xét và cho phép nộp lại."></app-page-header><article class="panel table-panel"><div class="table-wrap"><table><thead><tr><th>Mã SV</th><th>Họ tên</th><th>Thời gian nộp</th><th>Trạng thái</th><th>Điểm</th><th>Nhận xét</th><th></th></tr></thead><tbody>@for(item of items();track item.id){<tr><td>{{item.studentCode}}</td><td><b>{{item.studentName}}</b><small class="table-subtext">{{item.textContent}}</small></td><td>{{item.submittedAt|date:'dd/MM/yyyy HH:mm'}}</td><td><span class="badge" [class.danger]="item.isLate">{{item.status}}</span></td><td>{{item.score??'-'}}</td><td>{{item.feedback||'-'}}</td><td><button class="primary-button small-button" (click)="open(item)">Chấm bài</button></td></tr>}@empty{<tr><td colspan="7" class="empty">Chưa có bài nộp</td></tr>}</tbody></table></div></article>@if(modal()){<div class="modal-backdrop" (click)="modal.set(false)"><form class="modal" (click)="$event.stopPropagation()" (submit)="$event.preventDefault();save()"><div class="modal-heading"><div><h3>Chấm bài {{form.studentCode}}</h3><p>{{form.studentName}}</p></div><button type="button" class="icon-button" (click)="modal.set(false)"><span class="material-symbols-outlined">close</span></button></div><div class="form-grid"><label>Điểm<input type="number" [(ngModel)]="form.score" name="score"/></label><label>Trạng thái<select [(ngModel)]="form.status" name="status"><option>Graded</option><option>Returned</option><option>ResubmitRequired</option></select></label><label class="full-row">Nhận xét<textarea rows="5" [(ngModel)]="form.feedback" name="feedback"></textarea></label><label class="checkbox full-row"><input type="checkbox" [(ngModel)]="form.resubmissionAllowed" name="resubmissionAllowed"/> Cho phép sinh viên nộp lại</label></div><div class="modal-actions"><button type="button" class="secondary-button" (click)="modal.set(false)">Hủy</button><button class="primary-button">Lưu kết quả</button></div></form></div>}
` })
export class SubmissionsComponent implements OnInit { id = input.required<string>(); items = signal<SubmissionItem[]>([]); modal = signal(false); form: any = {}; constructor(private api: ApiService, private toast: ToastService) {} ngOnInit() { this.load(); } load() { this.api.get<SubmissionItem[]>(`/lecturer/assignments/${this.id()}/submissions`).subscribe(response => this.items.set(response.data)); } open(item: SubmissionItem) { this.form = { ...item, score: item.score ?? 0, status: item.status === 'Submitted' ? 'Graded' : item.status }; this.modal.set(true); } save() { this.api.put(`/lecturer/submissions/${this.form.id}/grade`, { score: Number(this.form.score), feedback: this.form.feedback || '', resubmissionAllowed: !!this.form.resubmissionAllowed, status: this.form.status }).subscribe({ next: () => { this.toast.show('Đã chấm bài', 'success'); this.modal.set(false); this.load(); }, error: error => this.toast.show(error.error?.message || 'Không thể chấm bài', 'error') }); } }
