import { Component, OnInit, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../core/services/api.service';
import { AssignmentItem, SubmissionItem } from '../../core/models/portal.models';
import { PageHeaderComponent } from '../../shared/page-header.component';
import { ToastService } from '../../core/services/toast.service';

@Component({ standalone: true, imports: [DatePipe, FormsModule, PageHeaderComponent], template: `
<app-page-header title="Bài tập" subtitle="Theo dõi hạn nộp, nộp bài và xem kết quả chấm."></app-page-header><div class="course-grade-grid">@for(item of items();track item.id){<article class="panel assignment-card" [class.overdue]="overdue(item)"><div class="panel-heading"><div><span class="eyebrow">{{item.courseCode}} · {{item.classSectionCode}}</span><h3>{{item.title}}</h3><p>{{item.content}}</p></div><span class="badge" [class.success]="item.studentSubmissionStatus==='Graded'" [class.danger]="overdue(item)&&!item.studentSubmissionStatus">{{item.studentSubmissionStatus||item.status}}</span></div><div class="detail-list"><div><span>Hạn nộp</span><b>{{item.dueAt|date:'dd/MM/yyyy HH:mm'}}</b></div><div><span>Điểm tối đa</span><b>{{item.maxScore}}</b></div><div><span>CLO</span><b>{{item.cloCodes.join(', ')}}</b></div>@if(item.studentScore!==undefined&&item.studentScore!==null){<div><span>Điểm</span><b>{{item.studentScore}} / {{item.maxScore}}</b></div>}</div>@if(item.studentFeedback){<div class="feedback-box"><b>Nhận xét của giảng viên</b><p>{{item.studentFeedback}}</p></div>}<button class="primary-button full" [disabled]="overdue(item)&&!item.allowLate" (click)="open(item)">{{item.studentSubmissionStatus?'Cập nhật bài nộp':'Nộp bài'}}</button></article>}@empty{<article class="panel empty-state"><span class="material-symbols-outlined">assignment</span><h3>Chưa có bài tập</h3></article>}</div>
@if(modal()&&selected();as assignment){<div class="modal-backdrop" (click)="modal.set(false)"><form class="modal" (click)="$event.stopPropagation()" (submit)="$event.preventDefault();submit()"><div class="modal-heading"><div><h3>Nộp bài: {{assignment.title}}</h3><p>Hạn nộp {{assignment.dueAt|date:'dd/MM/yyyy HH:mm'}}</p></div><button type="button" class="icon-button" (click)="modal.set(false)"><span class="material-symbols-outlined">close</span></button></div><label class="field-label">Nội dung<textarea rows="7" [(ngModel)]="textContent" name="textContent" placeholder="Nhập nội dung hoặc liên kết bài làm..."></textarea></label><label class="field-label">File đính kèm<input type="file" multiple (change)="chooseFiles($any($event.target).files)"/></label>@if(files.length){<div class="file-list">@for(file of files;track file.name){<span>{{file.name}} · {{(file.size/1024/1024).toFixed(2)}} MB</span>}</div>}<div class="modal-actions"><button type="button" class="secondary-button" (click)="modal.set(false)">Hủy</button><button class="primary-button" [disabled]="submitting()">Nộp bài</button></div></form></div>}
` })
export class StudentAssignmentsComponent implements OnInit { items = signal<AssignmentItem[]>([]); selected = signal<AssignmentItem | null>(null); modal = signal(false); submitting = signal(false); textContent = ''; files: File[] = []; constructor(private api: ApiService, private toast: ToastService) {} ngOnInit() { this.load(); } load() { this.api.get<AssignmentItem[]>('/student/assignments').subscribe(response => this.items.set(response.data)); } overdue(item: AssignmentItem) { return new Date(item.dueAt).getTime() < Date.now(); } open(item: AssignmentItem) { this.selected.set(item); this.textContent = ''; this.files = []; this.modal.set(true); } chooseFiles(list: FileList | null) { this.files = list ? Array.from(list) : []; } submit() { const item = this.selected(); if (!item) return; const form = new FormData(); form.append('textContent', this.textContent); this.files.forEach(file => form.append('files', file)); this.submitting.set(true); this.api.postForm<SubmissionItem>(`/student/assignments/${item.id}/submit`, form).subscribe({ next: () => { this.submitting.set(false); this.modal.set(false); this.toast.show('Nộp bài thành công', 'success'); this.load(); }, error: error => { this.submitting.set(false); this.toast.show(error.error?.message || 'Không thể nộp bài', 'error'); } }); } }
