import { Component, OnInit, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../core/services/api.service';
import { UserProfile } from '../../core/models/portal.models';
import { PageHeaderComponent } from '../../shared/page-header.component';
import { ToastService } from '../../core/services/toast.service';

@Component({ standalone: true, imports: [DatePipe, FormsModule, PageHeaderComponent], template: `
<app-page-header title="Hồ sơ cá nhân" subtitle="Cập nhật thông tin liên hệ; các trường học vụ quan trọng chỉ Admin được thay đổi."><button class="primary-button" (click)="save()" [disabled]="saving()"><span class="material-symbols-outlined">save</span> Lưu thay đổi</button></app-page-header>@if(profile();as item){<div class="profile-grid"><article class="panel profile-card"><div class="profile-avatar">{{item.fullName.charAt(0)}}</div><h2>{{item.fullName}}</h2><span class="badge success">{{item.role}} · {{item.status}}</span><div class="detail-list"><div><span>Tên đăng nhập</span><b>{{item.username}}</b></div><div><span>Email</span><b>{{item.email}}</b></div><div><span>Mã số</span><b>{{item.studentCode||item.lecturerCode||'-'}}</b></div><div><span>Khoa</span><b>{{item.facultyName||'-'}}</b></div><div><span>Chương trình</span><b>{{item.programName||'-'}}</b></div><div><span>Đăng nhập gần nhất</span><b>{{item.lastLoginAt|date:'dd/MM/yyyy HH:mm'}}</b></div></div></article><article class="panel"><div class="panel-heading"><div><h3>Thông tin liên hệ</h3><p>Các thay đổi được lưu trực tiếp vào hồ sơ tương ứng.</p></div></div><div class="form-grid"><label>Số điện thoại<input [(ngModel)]="form.phone"/></label><label>Ngày sinh<input type="date" [(ngModel)]="form.dateOfBirth"/></label><label class="full-row">Địa chỉ<input [(ngModel)]="form.address"/></label><label class="full-row">Ảnh đại diện URL<input [(ngModel)]="form.avatarUrl" placeholder="https://..."/></label><label class="full-row">Email phụ<input [(ngModel)]="form.secondaryEmail"/></label></div></article></div>}@else{<div class="skeleton-grid"><div class="skeleton"></div><div class="skeleton"></div></div>}
` })
export class ProfileComponent implements OnInit { profile = signal<UserProfile | null>(null); saving = signal(false); form: any = {}; constructor(private api: ApiService, private toast: ToastService) {} ngOnInit() { this.load(); } load() { this.api.get<UserProfile>('/profile').subscribe(response => { this.profile.set(response.data); this.form = { phone: response.data.phone || '', address: response.data.address || '', dateOfBirth: response.data.dateOfBirth?.slice(0, 10) || '', avatarUrl: response.data.avatarUrl || '', secondaryEmail: '' }; }); } save() { this.saving.set(true); this.api.put<UserProfile>('/profile', { ...this.form, dateOfBirth: this.form.dateOfBirth ? new Date(this.form.dateOfBirth).toISOString() : null }).subscribe({ next: response => { this.profile.set(response.data); this.saving.set(false); this.toast.show('Cập nhật hồ sơ thành công', 'success'); }, error: error => { this.saving.set(false); this.toast.show(error.error?.message || 'Không thể cập nhật', 'error'); } }); } }
